<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sector Dashboard Report</title>
    <style>
        * { font-family: DejaVu Sans, sans-serif; }
        body { color: #1b1b18; font-size: 12px; margin: 0; }
        h1 { font-size: 20px; margin: 0 0 2px; }
        h2 { font-size: 14px; margin: 20px 0 6px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        .muted { color: #666; font-size: 11px; }
        table { width: 100%; border-collapse: collapse; margin-top: 4px; }
        th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #e3e3e0; }
        th { background: #f4f4f2; font-size: 11px; text-transform: uppercase; letter-spacing: 0.03em; }
        td.num, th.num { text-align: right; }
        .totals td { font-size: 16px; font-weight: bold; }
        .header { border-bottom: 2px solid #1b1b18; padding-bottom: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>resiTrack — Sector Dashboard Report</h1>
        <p class="muted">
            {{ $scope }} &bull; Cagayan de Oro City<br>
            Generated {{ $generatedAt->format('F j, Y g:i A') }} by {{ $generatedBy }}
        </p>
    </div>

    <table class="totals">
        <tr>
            <td>Total Active Residents: {{ number_format($totalResidents) }}</td>
        </tr>
    </table>

    <h2>Vulnerability Sector Summary</h2>
    <table>
        <thead>
            <tr><th>Sector</th><th class="num">Count</th></tr>
        </thead>
        <tbody>
            @foreach ($sectorSummary['sectors'] as $sector)
                <tr>
                    <td>{{ $sector['name'] }}</td>
                    <td class="num">{{ number_format($sector['count']) }}</td>
                </tr>
            @endforeach
            <tr>
                <td>4Ps Beneficiary Households</td>
                <td class="num">{{ number_format($sectorSummary['fourps_households']) }}</td>
            </tr>
        </tbody>
    </table>

    <h2>Age Distribution</h2>
    <table>
        <thead>
            <tr><th>Age Group</th><th class="num">Residents</th></tr>
        </thead>
        <tbody>
            @foreach ($ageDistribution as $bracket)
                <tr>
                    <td>{{ $bracket['label'] }}</td>
                    <td class="num">{{ number_format($bracket['count']) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <h2>Audit Summary (last 30 days)</h2>
    <table>
        <tbody>
            <tr><td>Records Updated</td><td class="num">{{ number_format($auditSummary['records_updated']) }}</td></tr>
            <tr><td>New Registrations</td><td class="num">{{ number_format($auditSummary['new_registrations']) }}</td></tr>
            <tr><td>Duplicate Alerts Resolved</td><td class="num">{{ number_format($auditSummary['duplicates_resolved']) }}</td></tr>
            <tr><td>Program Applications</td><td class="num">{{ number_format($auditSummary['program_applications']) }}</td></tr>
        </tbody>
    </table>

    <p class="muted" style="margin-top: 30px;">
        This report was generated by the resiTrack Resident Profiling System for data-driven social
        service distribution and LGU compliance.
    </p>
</body>
</html>
